### ISSUE TITLE
Material - Arquitetura do boilerplate

### ISSUE THREAD

**Issue by RochaCarla** [BOSS-BigOpenSourceSibling/BigSibling#10]

**Comment by Joranhezon** [comment]
Criei essa versão simplificada do [diagrama](https://user-images.githubusercontent.com/8556291/57933140-d8d66b80-7892-11e9-8d58-a7eda60b099b.png) do boilerplate. Coloquei em português também para facilitar o entendimento, mas talvez algum sentido possa ter se perdido na tradução.

![Diagrama Boilerplate Simplificado](https://user-images.githubusercontent.com/20938170/88605313-e7e8aa00-d04f-11ea-88d1-70d63b607d3f.jpg)

**Comment by Joranhezon** [comment]
Links úteis para saber mais sobre o boilerplate:
- [Repositório do Boilerplate](https://github.com/lappis-unb/rasa-ptbr-boilerplate)
- [Documentação do Boilerplate](https://docs.rasaboilerplate.lappis.rocks/)

**Comment by BrunaNayara** [comment]
@Joranhezon Agora temos template de criação de conteúdo pra guiar a responsável da semana. 
Se quiser colocar nessa issue ou criar uma nova (pq aí vc consegue editar o comentário inicial) pra se organizar, fica a vontade <3

**Comment by BrunaNayara** [comment]
Não precisamos mais atualizar
