### ISSUE TITLE
Adicionar checkpoints com mentoras e mentoradas ao postmortem

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSibling/BigSibling#107]
Definimos que iremos fazer ainda nessa edição, mas é importante definirmos para próxima a frequência e como faremos.

**Comment by Joranhezon** [comment]
@carolinaferreira pra vc que quer Hacktoberfest. 😸

**Comment by carolinaferreira** [comment]
@Joranhezon e @RafaellaJunqueira abri um PR. Vocês podem dar uma olhada?
