### ISSUE TITLE
Material - UX de chatbot? 

### ISSUE THREAD

**Issue by RochaCarla** [BOSS-BigOpenSourceSibling/BigSibling#11]

**Comment by fabiolamfleury** [comment]
Fiz até então apenas um levantamento de materiais, preciso ainda sistematizar melhor isso.

Nessa página existem vários materiais: https://uxofchatbots.com/   (todos em inglês, seria interessante traduzi-los)

https://brasil.uxdesign.cc/ux-e-chatbots-boas-pr%C3%A1ticas-para-desenhar-interfaces-conversacionais-9beb0ba293f2

https://take.net/blog/designers/ui-e-ux-design-para-chatbots-e-interfaces-conversacionais

http://catarinasdesign.com.br/ux-e-a-tendencia-dos-chatbots-cases-e-reflexoes/

https://push.al/a-importancia-do-ux-para-criar-um-chatbot-de-sucesso/
Uma ordem interessante:
- Explicar primeiramente o que é UX
- Explicar o que é uma interface conversacional
- Explicar E exemplificar UX de chatbot
- Propor um pequeno exercício de fixação

**Comment by brunapinos** [comment]
Eu tenho essa apresentação que tem o básico de UX, talvez ajude: https://docs.google.com/presentation/d/18gUALprLK3sea6-V5pcmOolExFchU6z_dHohrUCIqFQ/edit?usp=sharing
