### ISSUE TITLE
Remodular aula sobre software livre

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSibling/BigSibling#123]
- [ ] As 4 liberdades do Software;
- [ ] Falar a diferença entre Software Livre e Open Source. Olhar [esse](https://www.gnu.org/philosophy/free-sw.en.html) link;
- [ ] Falar sobre licenças e dar alguns exemplos, mas nada muito específico. Tipo [essa](https://meet.google.com/linkredirect?authuser=0&dest=https%3A%2F%2Fpt.wikipedia.org%2Fwiki%2FWTFPL);

**Comment by BrunaNayara** [comment]
Já tá feito
