### ISSUE TITLE
Reunião 26/01/2021

### ISSUE THREAD

**Issue by clarissalimab** [BOSS-BigOpenSourceSibling/BigSibling#128]
# Reunião semanal

- **Data:** 26 de janeiro de 2021
- **Ata da reunião anterior**: [Link](https://github.com/BOSS-BigOpenSourceSister/BigSister/issues/122)
- **Participantes**:
  - Claris
  - Carla
  - Duda
  - Juliana
  - Iza
  - Nina
  - Ludi
  - Rafa
  - Debs

## Ata
* Ações do GNOME Challenge
  * FOSDEM (Claris e Nina) #133 
  * Publicações no twitter (Claris) #132 
  * Feedbacks dos avaliadores (Carla, Juliana, Bruna) #131 
* Atividades concluídas na semana
  * Revisão dos formulários de acompanhamento
* Próximas atividades

### Acompanhamento das ações pendentes da última reunião

- [ ] Material sobre Diversidade e Inclusão
- [x] Criar Formulário de Acompanhamento de Mentora/Mentorada
- [ ] Tarefa importante que ficamos de fazer (link para a issue criada)

@BOSS-BigOpenSourceSister/mentoras

**Comment by clarissalimab** [comment]
* Como podemos melhorar nosso processo de seleção para contemplar melhor as minorias?
* Planos para a entrega da fase 3

**Comment by RochaCarla** [comment]
- Como estruturar um framework para mentoras?

- Comunicação boss ?!

**Comment by Joranhezon** [comment]
- Discutir atividades semanais para que elas não virem um "dever de casa", tirando o foco da contribuição com a comunidade.
- Transparência sobre o progresso e atividades que estamos fazendo com as little sisters, principalmente as "fora do currículo";
- Como podemos incentivar mais as mentoradas a tentarem "resolver as dores que elas sentem na comunidade"?
- Redes sociais;

**Comment by RochaCarla** [comment]
During Phase Three of the Community Engagement Challenge, the GNOME goal is to offer as much support as possible to you and your project.  In doing so, we hope to raise awareness of your project, generate community support and elevate your project to whatever level you wish.  In that vein, we've designed several outreach opportunities.  These are all optional and will not be judged. 

Opportunity 1 - Conversation with Judges - Over the course of the next three weeks, we would like to arrange a meeting between your project team and the judges.  This is the opportunity to share your project and receive guidance and feedback directly from the judges.  If you would like to participate, please send me a few date/times that work for your team.  When making your suggestions, please keep in mind that our judges are based in PST, EST and UK time zones 
Opportunity 2 - Social Media takeover - We would like to share your project with every member of the GNOME and FOSS community. We have allocated one day to each team to "take over" the GNOME twitter/linkedin/Facebook account.  Our social media team will be posting your messages but we need you to create them! We will need a handful of posts (15+) from you, in your voice.  Themes should be Challenge/project related but can include:  1. Intro to team members, 2. a day in the life of your project 3.  How the idea of your project came about 4.  How you  incorporate, use your project. Remember that twitter has character limits, so break your messages up into shorter tweets.  Please let us know what day you would like your posts to go live.  Please include relevant hastags and tags.  
Opportunity 3 - Challenge Panel Discussion at FOSDEM (details TBD) -  FOSDEM takes place the first weekend in Feb. Traditionally it is hosted in Brussels, Belgium.  This year, it will be virtual! GNOME will have a booth and be promoting our products, speakers, and hosted events. During our booth time, we will be hosting a virtual Challenge themed chat.  This will include a short description of your project and a Q & A lead by me about your project, etc.  If a member of your team would like to participate, let me know and I will keep you posted on date/time/questions. 
Opportunity 4 - Hackfest at FOSDEM - During FOSDEM, we will also be promoting hackfests.  If you would like to host a hackfest for your project, let us know.  You will need to select a date/time and we can share with the community, the hackfest link and issues you hope to resolve.  While we can promote on your behalf, you'll need to manage the hackfest and invite users to participate, etc.  
These are just a few things that we are putting together to help support you during Phase 3.  If you have any other ideas or things you would like to see, please do not hesitate to reach out. 

I look forward to hearing from you.
