### ISSUE TITLE
Gnome Challenge - feedback com os avaliadores

### ISSUE THREAD

**Issue by RochaCarla** [BOSS-BigOpenSourceSibling/BigSibling#131]
Definir quem pode participar da call com os juizes (em inglês) e horários disponíveis 

Responder eles com essas informações 

Opportunity 1 - Conversation with Judges - Over the course of the next three weeks, we would like to arrange a meeting between your project team and the judges.  This is the opportunity to share your project and receive guidance and feedback directly from the judges.  If you would like to participate, please send me a few date/times that work for your team.  When making your suggestions, please keep in mind that our judges are based in PST, EST and UK time zones

**Comment by RochaCarla** [comment]
E-meail enviado-
we are eager to hear the feedback from the judges to improve our program.

We have a flexible agenda, but here are our availability for the following weeks:
January
28/01,  from  17:00  to 23:00 (London time zone)
29/01, from  19:00 to 23:00 (London time zone)

February
01/02 - 05/02, das 17:00 to 23:00 (London Time zone)

Any other suggestion of date/time, we can manage to participate.

**Comment by RochaCarla** [comment]
Agendado para dia 03/02 as 13h30 (horário de Brasilia)

Great! I am still waiting on feedback from the judges but wanted to share a draft of the agenda so that you can get an idea of how to prepare.  Please feel free to use the time to share your enthusiasm about your project, convey the project in a way that is not easily done on paper and obtain feedback from the judges.  If you wish to share any visuals or even put together a few slides, please feel free.  However, keep in mind that some of the judges may be calling in and not able to see your slides (we can share with them after the call).  

Tentative agenda: 

2 min - Welcome (Melissa)
3 min - Project team Intro (Project Team)
10 min - Overview of project (can be conversation or presentation) (Project Team)
How the project came about/what problem is being solved
How your project is building your community 
How your project encourages long term engagement in FOSS
How the project plans to scale in years to come
10 min - judges questions/feedback/any areas of clarification (Judges)
5 min - project questions/wrap up (Project Team)
Please let me know if you have any questions.
Best,

**Comment by jufajardini** [comment]
Observações das pessoas juradas:
- Qual o retorno que oferecemos para as pessoas mentoras, "what's in for them?"
- 4 a 6 horas semanais é um comprometimento de tempo grande. Como fazemos/ faremos para encontrar, treinar/qualificar, incentivar e manter mentoras por mais tempo?
-  Já consideramos o modelo de _pay it forward_ para ajudar a ter um fluxo de mentoras? As little sisters se tornando big sisters?
- Quais nossos planos e estratégias para escalar e para o futuro? Este é um projeto pensado só para o Brasil ou uma comunidade específica, ou ele pode ser reproduzido em outros contextos?
- O principal desafio que percebem é encontrar, treinar e manter pessoas mentoras engajadas.
--- consideramos ter mais de um projeto/ tecnologia possíveis, para ajudar pessoas mentoras a oferecerem mentoria mais dentro de sua zona de conhecimento/ conforto?
- Talvez uma forma de ajudar a reduzir a carga de dedicação para as pessoas mentoras é ter diferentes perfis de mentoras:
--- mentoria em relação a síndrome de impostora e empoderamento
--- mentoria da parte de contribuir para software livre// usar ferramentas de contribuição// estar em comunidade
--- mentoria técnica com um ou mais projetos
