### ISSUE TITLE
Gnome Challenge - publicação nas medias sociais

### ISSUE THREAD

**Issue by RochaCarla** [BOSS-BigOpenSourceSibling/BigSibling#132]
- [x] Escrever 15 posts sobre a boss (em ingles) pra ser publicado pela gnome
- [x] Sugestão de temas: sobre o time, como é o dia a dia das big/little sisters, como foi pensado no projeto, como usar o modelo de mentoria da boss, 
- [x] Indicar as datas ideais de publicação
- [x] Responder o email da gnome com as infos

Opportunity 2 - Social Media takeover - We would like to share your project with every member of the GNOME and FOSS community. We have allocated one day to each team to "take over" the GNOME twitter/linkedin/Facebook account.  Our social media team will be posting your messages but we need you to create them! We will need a handful of posts (15+) from you, in your voice.  Themes should be Challenge/project related but can include:  1. Intro to team members, 2. a day in the life of your project 3.  How the idea of your project came about 4.  How you  incorporate, use your project. Remember that twitter has character limits, so break your messages up into shorter tweets.  Please let us know what day you would like your posts to go live.  Please include relevant hastags and tags.

**Comment by clarissalimab** [comment]
Ideias:
* Publicação sobre processo de mentoria
* Publicação sobre processo de seleção de mentoradas

**Comment by jufajardini** [comment]
Lista dos tuítes do takeover do dia 10/03:

0 - Apresentação (pela gnome) https://twitter.com/gnome/status/1369619041556389891
1 - Saudação (1 tuíte): https://twitter.com/gnome/status/1369621557161598977
Apresentando a equipe:
2 - https://twitter.com/gnome/status/1369634140287463429
3 - https://twitter.com/gnome/status/1369641690756169733
4 - https://twitter.com/gnome/status/1369649245536542725
5 - https://twitter.com/gnome/status/1369656790099451907

6 - https://twitter.com/gnome/status/1369671892026617856
Background (?)
7 - https://twitter.com/gnome/status/1369686989931343876
8 - https://twitter.com/gnome/status/1369694538105688065
Materials:
9 - https://twitter.com/gnome/status/1369709641744187405
Stats:
10 - https://twitter.com/gnome/status/1369717188823715844
Stats/ impact - correlation to Gnome Challenge:
11 - https://twitter.com/gnome/status/1369724738768109583
Other initiatives that raised from it:
12 - https://twitter.com/gnome/status/1369739841366224897
13 - https://twitter.com/gnome/status/1369747387770675207
Real uses:
14 - https://twitter.com/gnome/status/1369754936905371648
15 - https://twitter.com/gnome/status/1369762485918605314
16 - https://twitter.com/gnome/status/1369770041546334208
Where to find more info:
17 - https://twitter.com/gnome/status/1369777585882730499

**Comment by jufajardini** [comment]
Sugestões de tópicos (aproveitando as ideias que Clarissa deu, também):
0 - O que é a BOSS/ proposta
1 - Falar sobre a equipe - 1
2 - Falar sobre a equipe - 2
3 - Motivações
4 - Sobre processo de mentoria
5 - Sobre o processo de seleção das pessoas mentoras
6 - Sobre a fase de preparação - mentoras
7 - Sobre processo de seleção de mentoradas
8 - como é o dia a dia das big/little sisters (Preciso de ajuda neste xD )
9 - como foi pensado no projeto
10 - como usar o modelo de mentoria da boss
11 - desdobramentos - talk like a boss - https://www.youtube.com/watch?v=YQMH11KXDCA
12 - desdobramentos - stats de contribuições?
13 - falar sobre 2ª rodada
14 - Divulgar as inscrições para mentorias
15 - Links com mais info

**Comment by jufajardini** [comment]
Documento de trabalho: [WIP tweets](https://docs.google.com/document/d/1eY3cfxWgC2ZOpup_vpxSJSgGYpT23rlnYWhFSfiNWyc/edit?usp=sharing)

**Comment by jufajardini** [comment]
Concluída, graças ao trabalho em equipe! /o/ <3
