### ISSUE TITLE
Gnome Challenge - urgente FOSDEM participação 

### ISSUE THREAD

**Issue by RochaCarla** [BOSS-BigOpenSourceSibling/BigSibling#133]
Vamos participar ? responder eles

Opportunity 3 - Challenge Panel Discussion at FOSDEM (details TBD) -  FOSDEM takes place the first weekend in Feb. Traditionally it is hosted in Brussels, Belgium.  This year, it will be virtual! GNOME will have a booth and be promoting our products, speakers, and hosted events. During our booth time, we will be hosting a virtual Challenge themed chat.  This will include a short description of your project and a Q & A lead by me about your project, etc.  If a member of your team would like to participate, let me know and I will keep you posted on date/time/questions. 

Opportunity 4 - Hackfest at FOSDEM - During FOSDEM, we will also be promoting hackfests.  If you would like to host a hackfest for your project, let us know.  You will need to select a date/time and we can share with the community, the hackfest link and issues you hope to resolve.  While we can promote on your behalf, you'll need to manage the hackfest and invite users to participate, etc.

**Comment by BrunaNayara** [comment]
Já aconteceu
