### ISSUE TITLE
Formulário De Inscrição de Mentoras e Organizadoras

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSibling/BigSibling#134]
Se basear(levemente) no formulário de inscrição de mentoras. Olhar também os problemas levantados no [post mortem](https://github.com/BOSS-BigOpenSourceSister/BigSister/blob/main/post_mortens/Temporada_1.md)
Conversar com a Anna e só sobre o formulário de pessoas mentoras do Outreachy.

Perguntas adicionais para serem colocadas:
- [ ] Explique porque você se acha capaz de lidar com pessoas com contexto social e vivencias diferentes das suas;
- [ ] Perguntar sobre experiências anteriores(O objetivo dessa pergunta é se a pessoa tem as habilidades para exercer o papel que quer);
- [ ] Uma pergunta de multiplas escolhas com habilidades que achamos importantes, para pessoa marcar;
- [ ] O que a pessoa quer fazer? Ser mentora, organizadora, social media, etc;

**Comment by jufajardini** [comment]
Ideias levantadas em uma das reuniões do form de acompanhamento

Ideias para o formulário de inscrição para mentoras
Você tem ao menos 4 horas semanais para dedicar à BOSS? (reunião de conteúdo, acompanhamento da mentorada, reunião de alinhamento)
Sente-se confortável em apresentar algum conteúdo para todas as participantes?
Sente-se confortável em apresentar algum dos conteúdos aos participantes?
[ ] FLOSS                [ ] Arquitetura do Boilerplate        [ ] Docker
[ ] Linux                [ ] Python (refatorar)            [ ] Outros
[ ] Git e Trunk dev.            [ ] Actions
[ ] Comunidades de software livre    [ ] Slots e Custom Actions
[ ] Introdução: chatbots e RASA    [ ] Dicas para debugs (refatorar. Passar desde o início)

Você gostaria de participar da organização da BOSS?
    Sim
    Não
(Se sim:)
Quais áreas gostaria de atuar?
[ ] Organização dos conteúdos no Drive       [ ] Organização do Github
[ ] Planejamento das Talk Like a Boss    [ ] Gerenciamento das redes sociais
[ ] Gerenciamento das reuniões semanais    [ ] Organização das fases de desafio (GNOME)
[ ] Desenvolvimento de documentação    [ ] Mentoria

**Comment by ludimila** [comment]
Sugestão para a pergunta de gênero:
![image](https://user-images.githubusercontent.com/1562636/107896606-81f14080-6f15-11eb-853b-bb93ba44080c.png)

**Comment by BrunaNayara** [comment]
Formulários criados
