### ISSUE TITLE
Documentação Gnome Parte 3

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSibling/BigSibling#144]
DATA LIMITE: 28/02/2020

- [ ] Intro da BOSS
- [ ]  O que avançamos da Fase 2 para Fase 3?
- [ ] Quais são nossos produtos hoje?
- [ ] Como podemos escalar o projeto? Apresentar o cronograma e explicar cada um dos passos, focando no porquê de fazermos isso.(Metodologia)
- [ ] Como nos auto-sustentamos hoje?
- [ ] Guia de mentoria
- [ ] Refinar o papel das mentoras. Deixar claro a lista de mentoras e suas funções, como mentoras para assuntos específicos.

**Comment by jufajardini** [comment]
Revisei e adicionei contribuições para o código de conduta e o guia para pessoas mentoras, achei que era mais seguro fazer como PR, pra evitar bagunças de conflitos...

**Comment by BrunaNayara** [comment]
Tudo enviado e certinho :D 
Link pro manual final https://drive.google.com/file/d/13hS6Sa5y9JzZbn6gOFCQt7DuOPRHKqcV/view?usp=sharing
