### ISSUE TITLE
Video da Boss na GNOME Ate 06/04/21

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSibling/BigSibling#147]
Showcase: We are asking that you submit a short (approx. 3 min) video for us to utilize in the showcase on April 7th.  This is optional and will not be judged but is intended for you to showcase your project. Feel free to use this time to grow your community, present your project and share a little about yourselves. Videos should be created in 16:9 aspect ratio and saved in .MP4 format. They can be shared through email as an attachment or with a download link to cechallenge@gnome.org.

- Roteiro: @jufajardini 
- Editar: 

Pode ser usado para divulgar, colocar no canal do youtube, twitter, etc.

**Comment by naiieandrade** [comment]
Ahh que top, @jufajardini ja tem algum roteiro? Ou alguém se candidatou? Tem que ser alguém que vez a primeira edição?

**Comment by jufajardini** [comment]
Oi @naiieandrade de momento ainda não teve praticalmente nenhuma evolução nesta tarefa. A @emmenezes começou a rascunhar algo aqui: https://docs.google.com/document/d/1rlPbamQ_LUh2qFdZXjGEIzA0czUMxoVoarJpzTidPL0/edit?usp=sharing
Acho que não precisa necessariamente ser quem esteve na primeira edição, na verdade ainda estamos bem abertas pra ideias de roteiro...

**Comment by jufajardini** [comment]
@naiieandrade e @emmenezes , coloquei mais algumas ideias no documento... Mas ainda não sabemos quem poderia editar, né. :( acho que acabou ficando muito em cima, foi mal :/

**Comment by clarissalimab** [comment]
* Your Name/Team members names
* Name of Project
* Short explanation of what your project is (like one or two sentences)
* Short statement about why you entered this challenge OR how your project will excite/engage the next generation of FOSS coders.
