### ISSUE TITLE
Escrever e enviar e-mail para para pessoas que se inscreveram no formulário de Mentoras

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSibling/BigSibling#151]
Por contexto:
- [x] Pessoa mentora de comunidade;
- [x] Pessoa mentora;
- [x] Pessoa de organizacão;
- [x] Pessoas com experiência de mentoria e contatos em grupos legais, mas não encaixa como pessoa mentora;
- [ ] Pessoas que não passaram.

[Tabela de pessoas selecionadas](https://docs.google.com/spreadsheets/d/1egdd-QihCiizeYwTFMDLSEaoSSwgK12DplC24_AgXWs/edit#gid=1549451737)

**Comment by ludimila** [comment]
**Mentor de comunidade**

Olá Terceiro,
Esperamos que esteja tudo bem, apesar de tudo.
Ficamos felizes em informar que agora você faz parte da comunidade BOSS como **pessoa mentora de comunidade**. Agradecemos a confiança e a vontade de se unir a nós. A BOSS é antes de tudo sobre pessoas.  Esse é o nosso código de conduta [link código de conduta]. 
A pessoa mentora de comunidades é responsável por [inserir responsabilidades].
Muito obrigada e até já!

**Comment by ludimila** [comment]
Olá Pessoa,
Esperamos que esteja tudo bem, apesar de tudo.
Ficamos felizes em informar que agora você faz parte da comunidade BOSS como pessoa mentora. Agradecemos a confiança e a vontade de se unir a nós. A BOSS é antes de tudo sobre pessoas. Esse é o nosso código de conduta [link código de conduta].
A pessoa mentora tem como algumas responsabilidades por exemplo [inserir responsabilidades].
Esse é o link para o grupos de pessoas mentoras no telegram [link do grupo]
Muito obrigada e até já! Estamos preparando nosso onboarding e informaremos todas as informações via email.

**Comment by ludimila** [comment]
**Pessoa que não passou**

Esperamos que esteja tudo bem, apesar de tudo.
Infelizmente viemos dar uma noticia não tão legal. No momento você não foi uma das pessoas selecionadas para mentorar na BOSS. Mas nada impede de nos acompanhar e tentar novamente nas próximas oportunidades.
Muito obrigada pela confiança e interesse.

**Comment by naiieandrade** [comment]
@ludimila eu gostei :relaxed:! Só atualizei o comentário ali em "... link para o grupo ..."

**Comment by jufajardini** [comment]
Sugestões neste:
> **Pessoa que não passou**
> 
> Olá Pessoa,
> Esperamos que esteja tudo bem, apesar de tudo.
> Agradecemos a confiança e a vontade de se unir à BOSS. Viemos dar uma noticia não tão legal. No momento, você não foi uma das pessoas selecionadas para mentorar na BOSS. Mas nada impede de nos acompanhar e tentar novamente nas próximas oportunidades.
> Muito obrigada pelo interesse em contribuir!

**Comment by BrunaNayara** [comment]
Mentor de comunidade

Olá Terceiro,
Esperamos que esteja tudo bem, apesar de tudo.
Ficamos felizes em informar que agora você faz parte da comunidade BOSS como pessoa mentora de comunidade. Agradecemos a confiança e a vontade de se unir a nós. A BOSS é antes de tudo sobre pessoas. Esse é o nosso código de conduta [link código de conduta].

Dentro do nosso programa, temos uma etapa de boas vindas a um contexto de comunidade de software livre. Depois temos a etapa de apresentação e resolução de problemas dentro desse contexto com um foco mais técnico. A última etapa do nosso programa é apresentar outras comunidades de software livre para que as nossas mentoradas possam seguir em frente fazendo um bom trabalho por aí.

Achamos que seu perfil encaixa como pessoa mentora de comunidades, que é responsável por apresentar outra, ou outras,  comunidades e fazer um onboarding, bem no estilo de sprint/workshop para que possam conhecer mais e talvez fazer a primeira contribuição.

Esse é o link para o grupo de pessoas mentoras no telegram [link do grupo]
Estamos preparando nosso onboarding e enviaremos todas as informações via email.

Muito obrigada e até já!
