### ISSUE TITLE
Escolher gerenciador de senha para times

### ISSUE THREAD

**Issue by ludimila** [BOSS-BigOpenSourceSibling/BigSibling#152]
Sugerido: Bitwarden

**Comment by clarissalimab** [comment]
Testei o Bitwarden pra uso pessoal e tem sido bem bom, não sei como fica pra times, mas vou pesquisar melhor sobre ele pra times.

![image](https://user-images.githubusercontent.com/15739610/113183308-3e833500-922a-11eb-81cc-789eadd4bf5f.png)

**Comment by Joranhezon** [comment]
@naiieandrade vale olhar o valor do bitwarden, como funciona para grupos, quantidade de pessoas, essas coisas. Estamos tendendo para ele

**Comment by knelasevero** [comment]
Eu pago o BitWarden para organizações por conta de uns outros projetos que toco. Pra mim foi 40 dólares por ano (plano família). Só 6 pessoas podem "sentar" em posições premium da organização (usar as funcionalidades premium). Mas tem como adicionar mais gente na organização, só não vão ter acesso a todas as funcionalidades.

**Comment by naiieandrade** [comment]
Pessoal, criei aqui a organização no Bitwarden. Mas tenho um levantamento pra fazer, que como é um plano gratuito todos entrariam por um login. Como só podem duas contas, tem a da BOSS e a minha, que até então está como "Proprietária" e o login da BOSS como "Gerente". Essa diferença dos perfis é importante porque ai não tem como alguém (que entrar pela BOSS) tirar o acesso dos dois emails. Questões de segurança.

Uma segunda sugestão seria criar uma planilha na conta da BOSS e adicionar o email de quem tem acesso. Porque dessa forma seria mais fácil ter acesso ao registro de atividades (caso deixe editável as senhas), e caso algum arquivo seja excluído por alguém, a conta da BOSS (criadora do arquivo) pode recuperar. Dessa forma todo mundo que vai ter acesso tem a partir da sua conta individual e não teria o passo a mais de ter outra senha para saber (pra logar no bitwarden).

E um último ponto seria apagar toda essa discussão para não deixar aberto as informações para possíveis ataques de segurança. :thinking:

**Comment by BrunaNayara** [comment]
O BitWarden foi o escolhido. 
Iremos usar a gratuita enquanto testamos se funciona bem dentro do nosso fluxo de trabalho.

**Comment by BrunaNayara** [comment]
@naiieandrade ficou responsável por isso
