### ISSUE TITLE
Divulgar vagas de pessoas mentoradas

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSibling/BigSibling#154]
Divulgar em:
- [x] Linkedin(@ludimila);
- [x] Twitter(@jufajardini);
- [x] Grupos de Telegram e Zap(Todo mundo)

### As imagens de divulgação estão na issue #155. Não esquecer de colocar a descrição das imagens em qualquer plataforma que vá fazer a divulgação (Telegram não tem nativamente)

O texto de divulgação tá no comentário da Duda aqui embaixo

**Comment by emmenezes** [comment]
Ooi, pessoal!
Participo de uma iniciativa chamada BOSS (Big Open Source Sibling) que visa introduzir pessoas de grupos subrepresentados ao software livre e fazê-las se sentirem acolhidas e confiantes na comunidade por meio de mentorias e outras atividades.

Nesse semestre vamos começar uma nova temporada e estamos abrindo vaga para participantes. Venha aprender com a gente conceitos de Git, trabalho colaborativo, trabalho assíncrono, como começar a contribuir com software livre e muito mais! Tudo isso feito por meio de uma mentoria personalizada, individual e de graça. :star: 

Quer colar com a gente? É só responder esse formulário pro processo de seleção. Os pré-requisitos são saber conceitos básicos de computação (if, for, while, etc) e ter disponibilidade semanal de x horas :) As inscrições vão até dia 16/04. https://docs.google.com/forms/d/e/1FAIpQLSc4ANbC732JcERp4yE_jn0nanIZ3XGbFgqbQRRrEtyLJMuCuw/viewform
