### ISSUE TITLE
Imagem de divulgação das vagas de participantes

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSibling/BigSibling#155]
Link: https://github.com/BOSS-BigOpenSourceSibling/BigSibling/issues/154

**Comment by naiieandrade** [comment]
- [ ]  ![36](https://user-images.githubusercontent.com/15681725/112644310-080d7a80-8e24-11eb-8f91-86b7f978b082.png)


- [ ]  ![39](https://user-images.githubusercontent.com/15681725/112644447-31c6a180-8e24-11eb-989b-38bb1e4cc2b3.png)


- [ ]  ![40](https://user-images.githubusercontent.com/15681725/112644469-38551900-8e24-11eb-96c1-fa2d616cb480.png)




Segue as imagens para divulgação que foram pra votação.
Até então a primeira tem 3 votos, a segunda 1 voto, e a terceira 2 votos.

**Comment by BrunaNayara** [comment]
Descrição em texto da imagem


```Imagem de divulgação da BOSS.
Título: Seja BOSS
Texto: Big Open Source sibling visa introduzir pessoas de grupos subrepresentados ao software livre com workshops semanais e fazê-las se sentirem acolhidas por meio de mentorias e outras atividades. Participe.
Nas bordas da imagem, há elementos que englobam o texto e há a logo da BOSS no canto inferior direito.```
