### ISSUE TITLE
Criar e divulgar formulário da BOSS Maratona

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSibling/BigSibling#156]

**Comment by BrunaNayara** [comment]
Texto para divulgação no twitter:

Em breve começará a segunda temporada da BOSS Maratona! Nele, a gente foca em ensinar os conceitos, técnicas e algoritmos mais conhecidos e utilizados em maratonas de programação.
Gostou da ideia? Quer ser aprender mais sobre? 
Preencha esse formulário e a gente entra em contato! 
O formulário ficará aberto até o dia 05 de abril e os resultados sairão na semana seguinte ao encerramento.

https://forms.gle/4JP4P7GdZrPkK4Tn7
