### ISSUE TITLE
Treinamento de mentoras

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSibling/BigSibling#157]
Topicos:

Semana 1 - Overview
- [x] O que é a BOSS? (@BrunaNayara)
- [x] Cronograma da pessoa mentora;(BOSS at a glance no manual) (@BrunaNayara)

Semana 2 - Contextualizar sobre proposito e importancia(12/04)
- [X] Dinâmica para conhecer novas pessoas mentoras e apresentar pessoas organizadoras. (@BrunaNayara )

Semana 3 - Mentoria(19/04)
- [x] Guia de mentoria. (@Joranhezon )
- [x] O que é Software livre (@clarissalimab )

Semana 4(26/04)
- [ ] O que e sindrome do impostor, confidence gap, etc; (@RochaCarla e Natércia)
- [ ] Guia de diversidade; (Natércia)

Semana 5 (03/05)
- [ ] Tecnicas de foco, trabalhar ansiedade, etc; (@jufajardini e @ludimila )

**Comment by BrunaNayara** [comment]
Comecei um esboço do material da primeira semana:
https://docs.google.com/presentation/d/1nq-9YRo45VXc7F7c1ag8fP5bLWQuy8xi1xF3u_1JmP4/edit?usp=sharing

**Comment by BrunaNayara** [comment]
Uma coisa que esquecemos de colocar nesse mês de treinamento de mentoras é sobre FOSS mesmo. Pq nem todas devem estar familiarizadas
