### ISSUE TITLE
Mini bio e descrição das pessoas mentoras

### ISSUE THREAD

**Issue by ludimila** [BOSS-BigOpenSourceSibling/BigSibling#158]
Mini bio falando em um tweet um pouco de você e uma foto sua para a gente usar como divulgação durante o período de inscrição que vai até 16/04/2021.

**Comment by jufajardini** [comment]
MiniBio **Juliana Fajardini**:
Graduada em SI (2014),  experiência em TI e empreendedorismo/startups: futebol de robos em ambiente de realidade mista; desenvolvimento de clientes; voluntariado com a OxenTI Menina; e atendimento a clientes. Desde dez/2020, a partir da Outreachy, trabalha com o Suricata (FOSS).
![ju_PB-menorzinha](https://user-images.githubusercontent.com/16976857/113631492-77277200-9661-11eb-829a-7cb91d58e48a.png)

**Comment by Joranhezon** [comment]
**Marina Joranhezon**
Engenheira de Software, Travesti e apaixonada em projetos sociais. Trabalhando há quase 3 anos na área, passou grande parte da sua carreira em Startups, atualmente na Bxblue. Em um relacionamento sério com a BOSS, animada para ser mentora mais uma vez nessa temporada.

Ps: Mãe de 5 gatos.

![image (12)](https://user-images.githubusercontent.com/20938170/113713413-b5527f00-96bd-11eb-9b2e-e9649ed15f17.png)

**Comment by knelasevero** [comment]
Lucas Severo ele/dele, he/him

Mantenedor em [external-secrets/kubernetes-external-secrets](https://github.com/external-secrets/kubernetes-external-secrets) e [external-secrets/external-secrets](https://github.com/external-secrets/external-secrets). Engenheiro Cloud Native na Container Solutions. Participando também do [EducaTRANSforma](http://www.educatransforma.com.br/capacitacao/).

<img src="https://user-images.githubusercontent.com/2432275/113728254-375e9a00-96f6-11eb-92ac-88037aa64f7e.png" width="400">

Twitter: https://twitter.com/canelasevero
Linkedin: https://www.linkedin.com/in/lucas-alves-1284a661/

**Comment by BrunaNayara** [comment]
![image](https://user-images.githubusercontent.com/4125846/113746878-2fdec700-96dd-11eb-8e6b-2910c92f1c08.png)

Bruna Moreira, ela

Bruna Moreira é engenheira de software, professora, e desenvolvedora de chatbot nas horas pagas. Nas horas vagas, dança forró, pole dance, tira cochilo na rede com seus gatos e agita comunidades de software livre: AcompanhaLegis, Big Open Source Sister, e PyLadies DF.

Linkedin: https://www.linkedin.com/in/brunamoreiral/



> Não vou ser big sibling, mas devo ficar de welcoming mentor

**Comment by crozarakamilla** [comment]
Kamilla Crozara (ela)
Engenheira de Software, líder de desenvolvimento de software no TJDFT, pythonista, entusiasta de frontend, apaixonada por Linux, lésbica, astrônoma amadora, gamer e mãe de oito gatos. 

![IMG_1379_600](https://user-images.githubusercontent.com/54539855/113749431-0bd0b500-96e0-11eb-944f-63dec28c6613.JPG)

**Comment by RochaCarla** [comment]
![Man with Smartphone YouTube Thumbnail](https://user-images.githubusercontent.com/5897389/113781718-7cd79300-9707-11eb-9f39-87a08045b01e.png)

Carla Rocha, ela

professora de Engenharia de Software na UnB,  entusiasta em Software Livre e contadora de histórias. Nas horas vagas, toca violão e ukulele, ama viajar, e ir em shows =)

**Comment by RafaellaJunqueira** [comment]
<img height="50%" width="50%" src="https://user-images.githubusercontent.com/43728276/113925110-fed7c280-97c0-11eb-8107-53e48af3268d.jpg">

Rafaella Junqueira, ela

Graduanda em Engenharia de Software, super fã da BOSS e, atualmente, estagia na área de forense digital. Ama dançar forró, fazer uns passeios natureza e tocar violão. Prefere Netflix a cinema, vôlei a futebol, hambúrguer a sushi e, definitivamente, telegram a whatsapp  =)

Pra todos verem:
Foto de uma mulher branca com cabelos ondulados de cor castanho escuro. Ela aparece sorrindo, vestindo uma roupa na cor azul marinho, sem mangas, e estampada com folhas na cor amarelo mostrada.

**Comment by GeovanaRamos** [comment]
<img src="https://user-images.githubusercontent.com/31005087/113930101-406b6c00-97c7-11eb-9ec4-ba82609adcf4.jpg" width=250>

Geovana Ramos, ela

Graduanda em Engenharia de Software e pesquisadora do laboratório LATITUDE/UnB. É uma das desenvolvedoras da assistente virtual Eva https://rasa.com/showcase/nspa-brazil/. Adora ouvir música, ver esportes, jogar videogame e realities 😂.

**Comment by terceiro** [comment]
![](https://avatars.githubusercontent.com/u/30027)

Antonio Terceiro (ele)

Desenvolvedor de Software Livre e membro do projeto Debian. Engenheiro de Software Sênior na Linaro Limited. Faz Python de dia, Ruby nas horas vagas, e Jiu-Jitsu nos períodos entre pandemias.

**Comment by babidomingues** [comment]
Bárbara Domingues (ela/dela)

Formada em Publicidade e Propaganda, atualmente Analista de Planejamento Comercial Sênior no PicPay. Experiências anteriores em empresas dos segmentos de Tecnologia e Telecom. Ama qualquer tipo de música, doguinhos, viajar e beber cerveja =) 

![IMG_2631](https://user-images.githubusercontent.com/82168875/114062559-0903ca80-986e-11eb-9e54-ae04c7b480b8.jpg)

**Comment by vitorandos** [comment]
Vítor Menezes, ele

Formado em Engenharia de Software. Trainee na CCR S.A. Experiência no desenvolvimento de softwares pedagógicos e em pesquisa em Governo Digital, Avaliação de Serviços e Ciência de Dados. Ama lo-fi, mobilidade urbana, aprender línguas e board games.

![curr](https://user-images.githubusercontent.com/15351084/114096603-521b4500-9895-11eb-9146-ac59ba341e5a.jpg)

Descrição da imagem: Foto do busto de homem preto com cabelo crespo num corte afro ou black power. Ele sorri levemente e usa uma camisa verde-escuro com uma listra vertical verde-claro e outra listra vertical laranja.

Linkedin: https://www.linkedin.com/in/menezesvitor/

**Comment by clarissalimab** [comment]
Clarissa Borges (ela/ dela)

Engenheira de Software, desenvolvedora no Projeto Houdini e na CommitChange, membro da GNOME Foundation e ganhadora do prêmio de Outstanding New Free Software Contributor 2019, da Free Software Foundation. Gosta de participar de comunidades FLOSS, jogar, principalmente com amigos, viajar, fofocar e resgatar animais de rua.

![image](https://user-images.githubusercontent.com/15739610/114103216-184f3c00-989f-11eb-8180-21525405172f.png)

Descrição da foto: Mulher branca de óculos, cabelos longos e sorrindo. Usa uma blusa cinza. Ao fundo, um quintal com algumas plantas.

Redes sociais:
Twitter: http://www.twitter.com/lborgesclarissa
Instagram: @clarissalimab

**Comment by andressavldrs** [comment]
Andressa, ela/dela

Engenheira de software, gosta de aprender com as pessoas e acredita que a tecnologia transforma vidas. Quer fazer parte da transformação para melhor. Adora um bom papo, comidas gostosas e bebidas geladas :) 

LinkedIn: https://br.linkedin.com/in/avaladares

![image](https://user-images.githubusercontent.com/9272663/114257299-6c3c4c80-9995-11eb-89c7-35f5e054cab1.jpeg)

Para todos verem: Mulher sorrindo com cabelos longos

**Comment by dehatanes** [comment]
Débora Atanes (ela/dela)
Debs é formada em Sistemas de Informação pela USP e hoje atua como Tech Lead na Outsmart Digital. É apaixonada por pessoas e adora conhecer gente nova! Dentro da área de tecnologia, se interessa por engenharia de software e ciência de dados. 

![foto](https://user-images.githubusercontent.com/17599203/114333464-b7ce3200-9b1e-11eb-91a1-edb875e0f316.jpeg)
Descrição da foto: Foto de busto de Débora em frente a um fundo branco. Ela é uma mulher branca, com cabelo castanho, longo e levemente bagunçado. Possui uma tatuagem de flores no ombro, veste uma regata preta e está com um sorrisão no rosto.

**Comment by andressafreires** [comment]
Dessa Freires (ela/dela)

Cientista de Dados, representante de inclusão, diversidade e cultura no PicPay. Acho que o melhor modo de me apresentar é dizendo que sou apaixonada por dados e pessoas! 

Descrição da foto: Uma mulher negra, sorrindo, com tranças no cabelo e tatuagens no braço e no tórax.

Redes sociais: https://linktr.ee/andressafreires

<img width="601" alt="Captura de Tela 2021-04-12 às 10 09 54" src="https://user-images.githubusercontent.com/21087570/114399435-4cfd1500-9b77-11eb-86dd-9df8feabc449.png">

**Comment by naiieandrade** [comment]
Naiara Andrade (ela/dela)
Engenheira de Software pela UNB


e hoje atua como Tech Lead na Outsmart Digital. É apaixonada por pessoas e adora conhecer gente nova! Dentro da área de tecnologia, se interessa por engenharia de software e ciência de dados.

Redes sociais para marcar
Instagram: @dehatanes
Linkedin: https://www.linkedin.com/in/deboraatanes/

**Comment by naiieandrade** [comment]
Naiara Andrade (ela/dela)
Engenheira de Software pela UNB, gosta de trabalhar com dados e entusiasta em finanças. Muito curiosa e adora aprender novas coisas, ter boas conversas, aceita indicação de séries e animes ;)

Redes sociais para marcar
Instagram: @naaiarandrade
Linkedin: https://www.linkedin.com/in/naiara-andrade/

![photo_2021-04-12_17-18-27_Easy-Resize com (1)](https://user-images.githubusercontent.com/15681725/114457544-8bfd8b80-9bb4-11eb-90c7-f2067e381d75.jpg)

Pra todos verem:
Foto de uma mulher branca com cabelos ondulados de cor castanho escuro. Ao fundo algumas árvores desfocadas. Ela aparece sorrindo, vestindo uma roupa na cor azul, com mangas, e com parte da estampada com o início da frase a mostra "Como to the..."

**Comment by keline01** [comment]
Keline Dantas, formada em Pedagogia, estudante do curso de Tecnologia em Análise e Desenvolvimento de Sistemas. Adoro viajar, comer, reunir os amigos e ajudar as pessoas, envolvida até a alma em projetos sociais.
![IMG_20200726_174026005](https://user-images.githubusercontent.com/82685985/115097343-d9089700-9eff-11eb-9d8c-d940776857ce.jpg)

Pra todos verem:
Foto de uma mulher de óculos, parda com cabelos longos, ondulados de cor preto. Ao fundo árvores de um parque e  a luz do por do sol. Ela aparece vestindo uma blusa coloria com  ombro de fora.

**Comment by pamellabiotec** [comment]
**Pâmella Araújo Balcaçar** graduada em Tecnologia em Informática e licenciada em Ciência Biológica. Tenho MBA em Perícia, Auditoria e Análise Ambiental. Gosto de viajar, ler, assistir série, beber um tereré bem gelado.

Minhas redes sociais: https://linktr.ee/pamellabiotec

![20160203_075352](https://user-images.githubusercontent.com/34974649/117746025-a9d10700-b1d9-11eb-89b4-f818e2be2241.jpg)

Foto descrição: estou no sítio dos meus avós materno, de cabelo molhado, ao natural, de blusa xadrez roxo. Ao fundo, tem uma árvore.

**Comment by amircardoso** [comment]
Amir Cardoso (elu/linguagem neutra)

Bacharel em Letras (UFMG) e estudante de Análise e Desenvolvimento de Sistemas (Newton Paiva). Me interesso por front-end, suporte técnico e metodologias ágeis.
Pessoa preta, não-binária e sapatão. Amante de gatos e cachorros e viciada em podcasts.

![757e066c-93c3-4dba-ad4e-d5fb287834bc](https://user-images.githubusercontent.com/57577175/119582974-04529180-bd9c-11eb-936c-5ed5e40c351e.jpg)

#ParaTodosVerem: Foto de uma pessoa. Ao fundo, janelas de vidro. No centro, pessoa negra de cabelo raspado, usando óculos retangular, colar e camiseta bege. o subtítulo também em vermelho, com letras menores escrito: “Lugares de fala: direitos, diversidades, afetos”. Na parte inferior, a esquerda há uma ilustração azul com 5 mãos empunhadas e a Direita está escrito em roxo: “julho 2020”. Fim da descrição.
