### ISSUE TITLE
Criar Roteiro para Video do GNOME da BOSS

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSibling/BigSibling#160]
Criar o roteiro para call que iremos fazer 02/04.

Exemplo:
 - Pessoa A: Eu quero cafééé
 - Pessoa B: ÉÉÉÉÉ
 - Pessoa C: Isso aqui tá uma porcaria

**Comment by ludimila** [comment]
Link pro roteiro: https://docs.google.com/document/d/1hLfba_DOdia-8OE-3ARxJHfsOx0oVQnhQ-XaYz1Ej5o/edit
