### ISSUE TITLE
Enviar E-mail Selecionadas BOSS Maratona

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSibling/BigSibling#164]

**Comment by RochaCarla** [comment]
Olá [Pessoa],

Esperamos que esteja tudo bem, apesar de tudo.
Ficamos felizes em informar que agora você faz parte da comunidade BOSS maratona. Agradecemos a confiança e a vontade de se unir a nós. A BOSS é antes de tudo sobre pessoas. Esse é o nosso código de conduta [link código de conduta].
Esse é o link para o grupo BOSS maratona no telegram [link do grupo]
Vamos iniciar as atividades na sexta feira, dia 09/04, as X horas na plataforma Microsoft Teams [link grupo]

Qualquer dúvida,  sugestão ou alguma demanda especifica, não hesite em entrar em contato conosco. 

Muito obrigada e até já!
