### ISSUE TITLE
Sync com ICTL para resgatarmos o prêmio GNOME

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSibling/BigSibling#166]
- [x] Alinhar com ICTL para entender como funciona;
- [x] Trazer na reunião para decidirmos que rumo tomamos.

**Comment by RochaCarla** [comment]
- https://www.ictl.org.br
- Eles cobram 10%, e incluem contador
- as instruções do Debian sobre transações internacionais  estão em https://salsa.debian.org/ictl-team/financeiro/
- em especial, https://salsa.debian.org/ictl-team/financeiro/-/blob/master/modelos/invoice-internacional.odt

**Comment by BrunaNayara** [comment]
A gente vai ser parceiro do ICTL
