### ISSUE TITLE
Entrevista: "Entrevista técnica"

### ISSUE THREAD

**Issue by BrunaNayara** [BOSS-BigOpenSourceSibling/BigSibling#198]
# Informações básicas

_As entrevistas técnicas para uma vaga de TI podem parecer uma caixinha de surpresas de onde saem termos como padrões de projeto, clean code, tratamento de exceções, estrutura de dados, solid, arquitetura, testes unitários, pareamento, testes de navegação._ 

- [x] **Entrevistada**:  @ludimila 
- [x] **Entrevistadoras**: @Joranhezon @belaaiza
- [x] **Backstage**: @RafaellaJunqueira 
- [x] **Data**: 24/06/2021
- [x] **Horário**: 19:00

# Preparação

## Criação do roteiro 
Para começar o roteiro, crie uma cópia do [template de roteiro](https://github.com/BOSS-BigOpenSourceSister/BigSister/blob/main/talk_like_a_boss/roteiro_entrevistas.md). 

- [x] Informações das entrevistadas: Nome e mini bio.
- [x] Coletar perguntas acerca do tema abordado
- [x] Verificar com as entrevistadas se existe alguma pergunta que não podemos deixar de colocar no roteiro

## Organização pré-entrevista

- [x] Marcar um horário de pelo menos duas horas (30 min de preparação + ~1 hora de entrevista + 20 min de feedback)
- [x] Criar o vídeo para a transmissão no youtube
- [ ] Criação da arte para o vídeo

## Divulgação
Após a criação prévia do vídeo da entrevista, já é possível gerar o link 

- [x] Texto base + informações específicas
- [x] Arte do vídeo
- [x] Link do vídeo

# Durante a entrevista

## 30 min de preparação
- [x] Apresentar a ferramenta de transmissão para todas envolvidas
- [x] Repassar o roteiro
- [x] Retirar qualquer pergunta que deixe alguém desconfortável

## Entrevista
- [x] Seguir o roteiro
- [x] Podem conversar, sintam-se confortáveis
- [ ] Lembrem de interagir com o público (curtir, comentar, se dirigir a audiência)

## Feedback
- [ ] Pergunte para todas as envolvidas se gostaram e o que pode ser melhorado
- [ ] Anotar pontos a melhorar e comentar com o restante da organização

**Comment by humrenan** [comment]
Quão importante é conhecer a empresa em que vai fazer entrevista?

**Comment by humrenan** [comment]
As empresas disponibilizam o que será cobrado na entrevista ou é tudo surpresa?

**Comment by pamellabiotec** [comment]
Como se adaptar para executar uma prova técnica em uma linguagem de programação determinada na qual não tenho habilidade e que não foi previamente divulgada?
