### ISSUE TITLE
[T2] Adicionar divisão de conteúdo dos vídeos

### ISSUE THREAD

**Issue by emmenezes** [BOSS-BigOpenSourceSibling/BigSibling#203]
Referência: **Adicionar divisão de conteúdo dos vídeos** #92

A ideia é semanalmente alguém se responsabilizar pela divisão do vídeo e deixar aqui nessa issue com o Link e as marcações de tempo. Após a primeira versão, qualquer outra pessoa pode melhorar adicionando outros momentos se achar necessário.

Referência dessa atividade por @giovanadionisio em [ChatBoss 1.3](https://github.com/BOSS-BigOpenSourceSibling/BigSibling/issues/92#issuecomment-720301939).

**Comment by BrunaNayara** [comment]
Vou adicionar isso como ponto de discussão para a próxima reunião. 
Como deixei #92 em aberto, vou fechar essa como duplicada
