### ISSUE TITLE
Definir como será a chamada para a contribuição

### ISSUE THREAD

**Issue by RafaellaJunqueira** [BOSS-BigOpenSourceSibling/BigSibling#208]
Teremos contribuição da galera da BOSS com outras comunidades open source. Selecionar como será a chamada para essas comunidades, ex:
- Abrir um forms?
- Chamar pelo twitter?
- Onde tirar dúvidas?

**Comment by emmenezes** [comment]
Para evitar dispersão das Little Siblings com uma oferta grande, optamos por deixar apenas as duas comunidades já selecionadas.
