### ISSUE TITLE
Entrevista: "Revolução da Cloud para não técnicos"

### ISSUE THREAD

**Issue by BrunaNayara** [BOSS-BigOpenSourceSibling/BigSibling#210]
# Informações básicas

- [x] **Entrevistada**: Mentorada do Kanela (Sarah) e Kanela
- [x] **Entrevistadoras**: Mentorada da @RafaellaJunqueira  e da @naiieandrade 
- [x] **Backstage**: @RafaellaJunqueira 
- [x] **Data**: 22/07/2021
- [x] **Horário**: 19:00 (às 19:30 vai live)

# Preparação

## Criação do roteiro 
Para começar o roteiro, crie uma cópia do [template de roteiro](https://github.com/BOSS-BigOpenSourceSibling/BigSibling/blob/main/talk_like_a_boss/template_roteiro_entrevistas.md). 

- [x] Informações das entrevistadas: Nome e mini bio.
- [x] Coletar perguntas acerca do tema abordado
- [x] Verificar com as entrevistadas se existe alguma pergunta que não podemos deixar de colocar no roteiro

## Organização pré-entrevista

- [x] Marcar um horário de pelo menos duas horas (30 min de preparação + ~1 hora de entrevista + 20 min de feedback)
- [x] Criar o vídeo para a transmissão no youtube
- [x] Criação da arte para o vídeo

## Divulgação
Após a criação prévia do vídeo da entrevista, já é possível gerar o link 

- [ ] Texto base + informações específicas
- [x] Arte do vídeo
- [x] Link do vídeo

# Durante a entrevista

## 30 min de preparação
- [x] Apresentar a ferramenta de transmissão para todas envolvidas
- [x] Repassar o roteiro
- [x] Retirar qualquer pergunta que deixe alguém desconfortável

## Entrevista
- [x] Seguir o roteiro
- [x] Podem conversar, sintam-se confortáveis
- [ ] Lembrem de interagir com o público (curtir, comentar, se dirigir a audiência)

## Feedback
- [ ] Pergunte para todas as envolvidas se gostaram e o que pode ser melhorado
- [ ] Anotar pontos a melhorar e comentar com o restante da organização

**Comment by knelasevero** [comment]
VOu jogando aqui umas coisas que discutimos e estamos levantando:

Normalmente a talk like a boss é uma entrevista do início ao fim né? Mas dessa vez acho que vamos mudar um pouco o formato. Já que é uma talk mais fechada.

Entao pensei no inicio vcs fazerem umas introduções, explicar o que é a boss, e a talk like a boss, e as introduções que tem geralmente nessas talks. Dai vcs começam perguntando pra Marina e pra mim sobre o que vai ser a talk e talks, e dai a gente segue pra talk em si.

dai dps a gente segue pra perguntas que podem ser feitas por vocês ou pelo chat.

**Comment by knelasevero** [comment]
Algumas perguntas que a gente pensou:

-Quais são suas preferências de cloud?
-Diferenças entre as clouds públicas
-Diferenças entre clouds públicas e empresas de clouds menores
-Como ter acesso à cloud enquanto pessoa, para testes, etc (Google Cloud e AWS têm o free tier)
-Vale a pena devs entenderem de Cloud?
-Que tipo de dev e outras profissões trabalham mais com Cloud?
