### ISSUE TITLE
Boss na PyLadies Con

### ISSUE THREAD

**Issue by BrunaNayara** [BOSS-BigOpenSourceSibling/BigSibling#233]
Estou no meio de uma reunião, mas essas são as coisas que precisamos preencher

**Proposal title**
Community management like a BOSS

**Session type**
Talk (20 minutes)

**Language**
English

**Abstract**
Engaging and contributing to FLOSS communities is scary enough. It being in a non-native language adds depth. Even more intimidating if you are from an underrepresented group. Now, being able to help people take their first steps is a drama. But guess what? We did it! How? That's what we wanna talk about in this presentation.

**Description**
Optional

**Notes**
Optional
These notes are meant for the organiser and won't be made public.
 
**Talk topic**
Communities
Indicate the main topic of your talk

**Level**
 Beginner,
 
**Resources**
Upload file

**Comment by BrunaNayara** [comment]
**Outline**

* What is BOSS (objetivos e key factors)
  * Aqui eu quero falar sobre diversidade, inclusão, barreira linguística e tecnológica
  * Lembrando que um dos objetivos é treinar as pessoas que são mentoras alé de capacitar mentoradas

* BOSS Cycle 
  * Aqui também quero dar uma ideia do que temos de coisas durante o ciclo pras pessoas terem uma ideia do tanto de trabalho kkkrying
  * Lecture semanal e mentoria semanal
  * Talk like a BOSS e sua importância
  * Aqui, a ideia é também falar da importância das mentoras
  
* Pessoas envolvidas
  * Por trás de toda a mentoria e aulas, precisamos de muito esforço na organização
  * Como fazemos essa organização
  * e como mantemos essas pessoas engajadas

* Dificuldades
  * Precisamos tanto treinar mentoras, como mentoradas como organizadoras
  * Nem todo mundo sabe fazer tudo e tudo bem 
    * Quebrar tarefas
    * Tutoriais
    * Tudo escritinho
    * Issues no github como grande facilitador
    * Tudo livre. FLOSS é key factor aqui
  * Dificuldades técnicas e como a colaboração pode sobrepor essa dificuldade

**Comment by BrunaNayara** [comment]
**Abstract Proposal**
Engaging and contributing to FLOSS communities is scary enough. It being in a non-native language adds depth. Now, being able to help people doing that is a drama. But guess what? We did it. How? That's what we wanna talk about in this presentation.

**Comment by belaaiza** [comment]
O que acha de adicionarmos a questão de ser de um grupo subrepresentado, sugestão:

Engaging and contributing to FLOSS communities is scary enough. It being in a non-native language adds depth. **Even more if you are form an underrepresented group**. Now, being able to help people doing that is a drama. But guess what? We did it. How? That's what we wanna talk about in this presentation.

**Comment by BrunaNayara** [comment]
Amei, vou botar na descrição da issue e mais tarde mando. 
Arrasou @belaaiza

**Comment by BrunaNayara** [comment]
Enviado. Adicionei ambas como co-speakers. 
Em breve deve chegar email
