### ISSUE TITLE
Criar tutorial de configuração do streamyard para entrevistas

### ISSUE THREAD

**Issue by BrunaNayara** [BOSS-BigOpenSourceSibling/BigSibling#53]

**Comment by RafaellaJunqueira** [comment]
Ainda vai ser feito esse tutorial? Tem só o do Jitsi na pasta "extra".

**Comment by BrunaNayara** [comment]
Acho que é bom ser feito, mas como estamos usando a conta da Carla, não sei se outras pessoas vão conseguir criar as transmissões da entrevista

**Comment by BrunaNayara** [comment]
Vou fechar essa issue pq estamos usando a conta da carla e pouca gente vai ter acesso de admin pra fazer isso. Se for necessário, abrimos outra no futuro
