### ISSUE TITLE
Criar um Onboarding para novas mentoras

### ISSUE THREAD

**Issue by clarissalimab** [BOSS-BigOpenSourceSibling/BigSibling#75]
# Motivação
Precisamos de uma apresentação que contextualize as mentoras sobre a BOSS: o que é, para quem é e seus objetivos, e que contemple orientações para a mentoria para que todas estejam alinhadas sobre o projeto.

# Informações básicas

- [ ] **Responsável**: @clarissalimab,  @brunapinos, @RochaCarla, @BrunaNayara 
- [ ] **Data**: A definir
- [ ] **Horário**: A definir
- [ ] **Conteúdo**: Guia definitivo da BOSS e como ser uma mentora

# Preparação

## Criação do conteúdo
Para começar a apresentação, crie uma cópia do [template de apresentação](https://docs.google.com/presentation/d/1vmnoDShQdG051p4HJaaoxIffP5i2ju-jOgBeDrOAemc/edit?usp=sharing). 

- [ ] Apresentação (slides)
- [ ] Apresentação prática (se for o caso)
- [ ] Conteúdo no repositório

## Organização pré-apresentação

- [ ] Marcar a data com as mentoras

Relacionada com a #64

**Comment by BrunaNayara** [comment]
Já temos um guia de mentoria no google drive com o nome `Organização e mentoria`. Vamos precisar revisar. Criarei ooutra tarefa pra isso
