### ISSUE TITLE
Configurar Assignbot para dar assign em alguma das mentoras nos PRs

### ISSUE THREAD

**Issue by Joranhezon** [BOSS-BigOpenSourceSibling/BigSibling#79]
Alguns PR's de mentoradas estão ficando no limbo até que alguma das mentoras veja. Acaba que isso ocorre por uma falta de notificar que esse PR foi feito.

Poderiamos configurar um assignbot simples, inicialmente com meu usuário apenas, para que o bot realize o assign e possamos ver esse PR. Dai cada mentora vai colocando seu usuário no assignbot quando quiser.

[O que é assignbot?](https://github.com/marketplace/actions/auto-assign-action)

Infelizmente, não achei um tutorial em pt.

**Comment by BrunaNayara** [comment]
É uma boa. Acho que marcando a gente no comentário já resolve. O difícil é todas lembrarem né kkkk

Outra coisa, acho que é legal pedirmos pra elas mandarem lá no grupo, até pra incentivar outras (?)

**Comment by BrunaNayara** [comment]
Vamos repensar o projeto que vai ser usado pra introdução das participantes. Verremos a necessidade no futuro
