### ISSUE TITLE
Material - Chatbot: conceitos 

### ISSUE THREAD

**Issue by RochaCarla** [BOSS-BigOpenSourceSibling/BigSibling#9]

**Comment by Joranhezon** [comment]
Alguns links interessantes que achei em minha pesquisa e utilizei na criação dos slides:
- [O que é um Chatbot](https://www.oracle.com/br/solutions/chatbots/what-is-a-chatbot/)
- [Linguagem natural e inteligência artificial em chatbot](https://help.blip.ai/docs/en/ai/nlp/conceitos-basicos-nlp-e-ai/)
- [Boas práticas ao criar chatbot](https://medium.com/botsbrasil/boas-pr%C3%A1ticas-ao-criar-chatbots-com-intelig%C3%AAncia-artificial-inten%C3%A7%C3%B5es-entidades-d563309a5451)
- [Chatbot voltado para interação com cliente](https://rockcontent.com/blog/chatbots/)

**Comment by naiieandrade** [comment]
https://github.com/BOSS-BigOpenSourceSister/BigSister/blob/main/docs/conteudos/conceitos-chatbot.md

A @RafaellaJunqueira já colocou na pasta docs.

**Comment by BrunaNayara** [comment]
Eu tô com esse conteúdo localmente e um PR em rascunho. 
Vou tentar fechar essa semana pra fechar essa issue.

**Comment by dehatanes** [comment]
@BrunaNayara preciso te ajudar nessa, vamos marcar uma hora pra fechar isso de vez essa semana?

**Comment by RafaellaJunqueira** [comment]
> https://github.com/BOSS-BigOpenSourceSister/BigSister/blob/main/docs/conteudos/conceitos-chatbot.md
> 
> A @RafaellaJunqueira já colocou na pasta docs.

Coloquei vazio mas achei melhor não apagar a issue porque estava em andamento, né... depois a gente apaga o doc de agr se não for utilizado ;)
